### PR TITLE
Test on multiple release channels of Rust

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by netvl** [comment]
This is nice, however, I'm not sure how this would interact with doc uploads (won't they get uploaded thrice?)

I really want to integrate `travis-cargo` tool described [here](http://huonw.github.io/blog/2015/05/travis-on-the-train-part-2/) as soon as I have some free time (maybe even today), so I probably will add testing on different channels then.

**Comment by frewsxcv** [comment]
> This is nice, however, I'm not sure how this would interact with doc uploads (won't they get uploaded thrice?)

Would anything bad happen in this scenario?

**Comment by netvl** [comment]
I don't know, but different rustdoc versions would produce different documentation. I'm not experienced enough with it to know whether it can cause any issues, but I'd want to be careful here.

And `travis-cargo`, in particular, allows uploading documentation only for specific release channel.

**Comment by netvl** [comment]
I finally found time and switched travis builds to use travis-cargo, so I'm closing this. Thank you very much for your pull request anyway!

**Pull request closed without merging**
