### PR TITLE
Move EventReader integration tests into a separate file and enable them

### PR DESCRIPTION
**Pull request by gkoz**
With these tests enabled people can hack on the parser more confidently.
A drawback of using `include_bytes!` is that cargo doesn't notice changes to any included files (this might just be a cargo bug).

### CODE REVIEW

**Comment by gkoz** [comment]
`sample_4` might actually be expected to fail, I'm not sure.

**Comment by netvl** [comment]
Thank you very much, and sorry for the long wait! The basic idea is really great - while these tests were initially were initially intended only for debug printing, eventually I did want to have some test infrastructure to check parser output. However, I'm not sure I want to bind expected events to their string representation. Do you think it is possible to include event values directly to Rust code somehow so they are compiled too? I think `include!()` should be helpful here.

**Comment by gkoz** [comment]
Note that the string representation is defined in the same file by implementing `Display` for the wrapper newtype `Event` so it doesn't depend on the way `XmlEvent` is displayed, although it does depend on the representation of element and attribute names. That could be eliminated as well. If we don't depend on the string representations from the library, what's the upside of specifying the outcomes in Rust?

**Comment by gkoz** [comment]
This leaves us with relying on the way `XmlVersion` and `Error` are displayed, not that unreasonable.

**Comment by gkoz** [comment]
Here's the issue for that `include_bytes` problem: https://github.com/rust-lang/cargo/issues/1510

**Comment by netvl** [comment]
> Note that the string representation is defined in the same file by implementing Display for the wrapper newtype Event so it doesn't depend on the way XmlEvent is displayed

Ah, sorry, I somehow missed that. Then it is acceptable. Thanks!

**Pull request merged**
