### PR TITLE
Added newline escape to dispatch_for_attribute

### LINKED ISSUE #153: end-of-line in attribute
In the Readme.md you said "attribute value normalization is not performed, and end-of-line characters are not normalized too.". Is there a reason why end-of-line characters are not normalized and is there a way to manually write the normalized form without disabling normalization completely?

The Problem I'm facing is that I have to create an XML which contains an attribute like this:
```
testOp()&#xA;after
```
("\&#xA;" is the normalized Version of a "\n")

Reading a file is not a Problem as the Parser correctly normalizes it to "\n". 
Writing it on the other hands leads either to a newline in the file when using "\n" (as it is not getting normalized) or to "\&amp;#xA;" using "\&#xA;" (cause the & is being normalized).

### PR DESCRIPTION
**Pull request by mettke**
* \&#xA; for \n
* \&#xD; for \r

Fixed #153

### CODE REVIEW

**Comment by netvl** [comment]
I would appreciate some tests (like [this](https://github.com/netvl/xml-rs/blob/master/tests/event_reader.rs#L271) one); otherwise looks good, thanks!

I just have re-read the spec again and it's actually not "attribute value normalization" which is only applicable for parsing, it's just behavior of the writer, so it is not covered by any spec. Not that fixing it isn't a good thing, of course. Another interesting fact is that, it seems, bare newlines are allowed in attribute values, they just have to be parsed as spaces. At least that's how I understand the spec's wording. This is just a side note, a bit of trivia :)

**Comment by mettke** [comment]
@netvl I didn't know exactly want kind of test you want so I just added one which creates Elements containing the special characters and tests whether they are escaped correctly. 

Feel free to add more specifics if it's not want you meant.

**Comment by netvl** [comment]
Yes, looks great, thanks! I gave a wrong link, sorry, for some reason I had been thinking about parser at that time.

**Comment by netvl** [comment]
Just released v0.6.1 to crates.io with this change.

**Pull request merged**
