### PR TITLE
Make position tracking more precise and expose the position to clients

### LINKED ISSUE #37: Please expose a function to get the current position when parsing
This would be very helpful to construct error messages when figuring out where in a multi-megabyte XML monstrosity a parser goes off the tracks. It looks like it should be a relatively straightforward change too.

### PR DESCRIPTION
**Pull request by gkoz**
This is supposed to resolve #37.
(It's branched off of #86 for now so incorporates the commit from there that will go away after merging and rebasing)

### CODE REVIEW

**Comment by netvl** [comment]
Thank you very much! Since this PR depends on #86 let's wait until it is resolved (I have a few questions there).

**Comment by gkoz** [comment]
Rebased.

**Comment by netvl** [comment]
Thanks again! I reviewed this PR again and everything is really nice. One thing remains, though - I think that `GetPosition`/`get_position()` should be renamed to just `Position`/`position()` per official [conventions](http://aturon.github.io/style/naming/README.html#getter/setter-methods-[rfc-344]).

**Comment by gkoz** [comment]
Renamed the trait to `Position`, the struct to `TextPosition`, while there, squashed the commit that added `#[inline]`.

**Comment by netvl** [comment]
Great, thank you very much!

**Pull request merged**
