### PR TITLE
Updates for recent Rust and dependency changes

### PR DESCRIPTION
**Pull request by mbrubeck**
* Fix `private_in_public` warnings
* Allow bitflags 0.6

### CODE REVIEW

**Comment by netvl** [comment]
Sorry for the delay!

Looks good to me, but is there a particular reason why `bitflags = "0.6"` dependency can't be used?

**Comment by mbrubeck** [comment]
`bitflags = "0.6"` would be fine too.  I thought it might be useful to allow 0.5 in case some want to update xml-rs without updating bitflags (in case they have other dependencies that are still on 0.5).  But in practice I don't think it makes any difference.

**Comment by mbrubeck** [comment]
Changed to `bitflags = "0.6"`.

**Comment by netvl** [comment]
Thanks! Will release in a minute.

**Pull request merged**
